name: Fx.Tween.Toggle
author: Ryan Florence
category: Effects
tags: [toggle, tween]
docs: http://moodocs.net/rpflo/mootools-rpflo/Fx.Tween.Toggle
demo: http://moodocs.net/rpflo/mootools-rpflo/Fx.Tween.Toggle
current: 1.0